apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testgo0311 
  janus-idp.io/tekton: testgo0311
  backstage.io/kubernetes-id: testgo0311
  backstage.io/kubernetes-namespace: testgo0311 
  app.kubernetes.io/part-of: testgo0311
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  