apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testgo0311
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testgo0311 
  name: testgo0311
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testgo0311
    weight: 100 
